# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.1
# running this YAML files requires administrator privileges
# Checks for presence of environment variable and removes it if it's present.
properties:
  configurationVersion: '0.1.0'
  assertions:
    - resource: Environment
      directives:
        module: PSDscResources
      settings:
        Name: 'DSC_EXAMPLE'
        Ensure: 'Present'
        Value: 'Desired State Configuration'
        Target: 'Machine'
  resources:
    - resource: Environment
      directives:
        module: PSDscResources
      settings:
        Name: 'DSC_EXAMPLE'
        Ensure: 'Absent'
        Value: 'Desired State Configuration'
        Target: 'Machine'